// Homepage
export const GET_COVER_PAGE_ENTRIES = 'GET_COVER_PAGE_ENTRIES';

// User actions
export const SET_USER = 'SET_USER';
export const SET_TOKEN = 'SET_TOKEN';
export const LOGOUT = 'LOGOUT';
export const TOKEN_SESSION = 'TOKEN_SESSION';
export const SET_CURRENT_PATHNAME = 'SET_CURRENT_PATHNAME';

export const GET_FAQ_ENTRIES = 'GET_FAQ_ENTRIES';
export const GET_ARTICLES_PUBLICATIONS_ENTRIES = 'GET_ARTICLES_PUBLICATIONS_ENTRIES';
export const GET_DEFINITION_ENTRIES = 'GET_DEFINITION_ENTRIES';

// Contact actions
export const FORM_RESPONSE = 'FORM_RESPONSE';
